### ISSUE TITLE
NECESITO AYUDA

### ISSUE THREAD

**Issue by alexissosa88** [adrianAnyansi/LeagueAutoTimer#1]
Hola, no logro hacer funcionar en OBS la aplicación. Además, ¿como lo aplico para mi propia liga con las partidas de League of legendes en el cliente? Gracias!

**Comment by adrianAnyansi** [comment]
Hi if I understand your comment, you are asking how to use this in OBS and with the League Client.

This project does not do that. It gets the timer from the Riot Worlds broadcast for Live View / Co-Streams. So streamers commenting a Riot game have an accurate timer from the broadcast/stream automatically, like twitch.tv/meteos did for MSI.

Is there a reason you want a timer from the League Client/Game? If you could explain what to want to do, I can try to help.
